name: Deploy to Ec2 

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/github-actions-cicd-react-aws-ec2.git
          git pull origin main
          npm install
          npm run build --production
          sudo cp -R build/ /var/www/vhosts/frontend/
          sudo service nginx restart        